//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luu_xoa_sua_thong_tin_nhan_vien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemSinhVien1
    {
        public int id { get; set; }
        public string hoten { get; set; }
        public double diemtoan { get; set; }
        public string diemsinh { get; set; }
        public string diemly { get; set; }
        public string diemanh { get; set; }
    }
}
