//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luu_xoa_sua_thong_tin_nhan_vien
{
    using System;
    using System.Collections.Generic;
    
    public partial class hocsinh
    {

        public int maHS { get; set; }
        public string tenHS { get; set; }
        public string diaChi { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string dienThoai { get; set; }
        public hocsinh(string hoTen, Nullable<System.DateTime> ngaySinh, int mssv, string diaChi, string sdt)
        {
            this.maHS = maHS;
            this.tenHS = hoTen;
            this.diaChi = diaChi;
            this.ngaySinh = ngaySinh;
            this.dienThoai = sdt;
        }

    
    }
}
